#!/usr/bine/env bash

git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
git clone https://github.com/Captn138/zshrc.git
mv zshrc/.zshrc ~
mv zshrc/aussiegeek.zsh-theme ~/.oh-my-zsh/themes/
rm -rf zshrc
source ~/.zshrc
