#!/bin/bash

sudo apt install curl zsh
sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
git clone https://github.com/Captn138/zshrc.git
mv zshrc/.zshrc ~
mv zshrc/aussiegeek.zsh-theme ~/.oh-my-zsh/themes/
rm -rf zshrc
source ~/.zshrc
